//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treenks.Bralek.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Treenks.Bralek.Web.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are receiving this email, because you choose to recover your lost password. &lt;br/&gt;
        ///&lt;a href=&quot;{0}&quot;&gt;Reset password here&lt;/a&gt;.
        /// </summary>
        public static string BODY_RESET_PASSWORD_EMAIL {
            get {
                return ResourceManager.GetString("BODY_RESET_PASSWORD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already in use.
        /// </summary>
        public static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address does not belong to any user.
        /// </summary>
        public static string EMAIL_NOT_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string EMAIL_NOT_VALID {
            get {
                return ResourceManager.GetString("EMAIL_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide an email.
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can&apos;t load your subscriptions at this time, try again later.
        /// </summary>
        public static string ERROR_LOADING_ITEMS {
            get {
                return ResourceManager.GetString("ERROR_LOADING_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can&apos;t mark your items as read at this time, try again later.
        /// </summary>
        public static string ERROR_MARK_ITEMS_READ {
            get {
                return ResourceManager.GetString("ERROR_MARK_ITEMS_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required.
        /// </summary>
        public static string FIELD_REQUIRED {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are trying to import is not a valid google reader file.
        /// </summary>
        public static string GOOGLE_READER_FILE_NOT_VALID {
            get {
                return ResourceManager.GetString("GOOGLE_READER_FILE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong trying to import your feeds..
        /// </summary>
        public static string IMPORT_ERROR {
            get {
                return ResourceManager.GetString("IMPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you import your files, it can take up to ten minutes to see your feeds.
        /// </summary>
        public static string IMPORT_INFO {
            get {
                return ResourceManager.GetString("IMPORT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read your favorite content in one place.
        /// </summary>
        public static string LANDING_PRODUCT_INFO {
            get {
                return ResourceManager.GetString("LANDING_PRODUCT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start reading your favorite content in.
        /// </summary>
        public static string LANDING_PRODUCT_INFO2 {
            get {
                return ResourceManager.GetString("LANDING_PRODUCT_INFO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you already have an account..
        /// </summary>
        public static string LANDING_PRODUCT_INFO3 {
            get {
                return ResourceManager.GetString("LANDING_PRODUCT_INFO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new unread items, click to.
        /// </summary>
        public static string NEW_ITEM_UNREAD {
            get {
                return ResourceManager.GetString("NEW_ITEM_UNREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items left to read.
        /// </summary>
        public static string NO_ITEMS_LEFT_TO_READ {
            get {
                return ResourceManager.GetString("NO_ITEMS_LEFT_TO_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was not changed, maybe your current password was not ok.
        /// </summary>
        public static string PASSWORD_CHANGE_ERROR {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string PASSWORD_CHANGED {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords are not the same.
        /// </summary>
        public static string PASWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ReCaptcha couldn&apos;t be validated, please try again.
        /// </summary>
        public static string RECAPTCHA_INVALID {
            get {
                return ResourceManager.GetString("RECAPTCHA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reseted successfully.
        /// </summary>
        public static string RESET_PASSWORD_COMPLETE {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong trying to reset your password, please start the process from the beginning, perhaps your token has expired.
        /// </summary>
        public static string RESET_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with a reset password link has been sent to your account.
        /// </summary>
        public static string RESET_PASSWORD_SENT {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bralek - Reset password.
        /// </summary>
        public static string SUBJECT_RESET_PASSWORD_EMAIL {
            get {
                return ResourceManager.GetString("SUBJECT_RESET_PASSWORD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is not a valid url format.
        /// </summary>
        public static string URL_NOT_VALID {
            get {
                return ResourceManager.GetString("URL_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email or password, please try again.
        /// </summary>
        public static string USER_PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("USER_PASSWORD_WRONG", resourceCulture);
            }
        }
    }
}
