// <auto-generated />
namespace Treenks.Bralek.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddUnreadItemsToUserSubscription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUnreadItemsToUserSubscription));
        
        string IMigrationMetadata.Id
        {
            get { return "201306062121071_AddUnreadItemsToUserSubscription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
