// <auto-generated />
namespace Treenks.Bralek.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ReleaseOneDbModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReleaseOneDbModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201306022000537_ReleaseOneDbModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
